[database]
url = "mysql://usrname:passwd@localhost/db_name?ssl-mode=disabled"
min_connections = 1
max_connections = 5
connect_timeout = 2
idle_timeout = 60

[app]
token_secret = "0000000000000000000000000000000000000000000000000000000000000000"

[esi]
client_id = "EVE Client ID"
client_secret = "EVE Client Secret"
url = "http://localhost:3000/auth/cb"

[sse]
url = "http://localhost:8000"
secret = "0000000000000000000000000000000000000000000000000000000000000000"

[fleet_updater]
enable = true
min_in_fleet = 8

[skill_updater]
enable = true
runtime = 86400

[srp_updater]
enable = true
interval_seconds = 300

[incursion_updater]
enable = true
interval_seconds = 3600

[janice]
api_key = "YOUR_JANICE_API_KEY"
